Parameters:
  BucketNameParameter:
    Type: String
    Description: 'A bucket name to set.'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [
          !Ref BucketNameParameter, 'dummy', 'suffix'
        ]
      ]
